title = "Primary Care Workforce Dashboard"

[database]
sql_database = "Data_Lab_NCL_Dev"
sql_schema = "JakeK"

[gpw]

[gpw.main]
sql_table_main = "wf_pc_pcwd_gpw_main"
sql_table_columnmap = "wf_pc_pcwd_columnmap"

