title = "Primary Care Workforce Dashboard"

[archive]
archive_source = "False"

[database]
sql_database = "Data_Lab_NCL_Dev"
sql_schema = "JakeK"

[gpw]

[gpw.main]
pipeline_name = "GPW Main Data"
sql_table_main = "wf_pc_pcwd_gpw_main"
sql_table_columnmap = "wf_pc_pcwd_columnmap"

[gpw.age]
pipeline_name = "GPW Age Data"
sql_table_age = "wf_pc_pcwd_gpw_age"

[pcn]
pipeline_name = "PCN Data"
sql_table_pcn = "wf_pc_pcwd_pcn"

[nwrs]
pipeline_name = "NWRS Metadata"
sql_table_nwrs = "wf_pc_pcwd_nwrs"